Repository munich-quantum-toolkit/predictor, pull requests merged in 2023-12, with the labels that each got.

#172 🐛 added mean errors in device calibration file
  src/mqt/predictor/Calibration.py
Labels: bug

#173 🔧 Adjust codecov config
  .github/codecov.yml
  src/mqt/predictor/Calibration.py
Labels: enhancement, continuous integration

#174 🩹 Fix coverage collection
  .github/codecov.yml
  .github/workflows/coverage.yml
  pyproject.toml
Labels: bug, continuous integration

#175 ✅ Improved Test Coverage
  src/mqt/predictor/evaluation.py
  src/mqt/predictor/ml/helper.py
  tests/compilation/test_helper_rl.py
  tests/device_selection/test_helper_ml.py
  tests/test_evaluation.py
  tests/test_result.py
  tests/test_reward.py
Labels: enhancement, continuous integration

#176 🎨 improved RL Predictor qcompile method signature
  src/mqt/predictor/rl/helper.py
  tests/compilation/test_predictor_rl.py
Labels: documentation, enhancement
