Repository munich-quantum-toolkit/predictor, pull requests merged in 2024-02, with the labels that each got.

#183 🎨 ✨ Improvement of Action Space: BQSKit and Qiskit O3 Optimization
  pyproject.toml
  src/mqt/predictor/rl/Predictor.py
  src/mqt/predictor/rl/PredictorEnv.py
  src/mqt/predictor/rl/helper.py
  tests/compilation/test_integration_further_SDKs.py
Labels: enhancement, feature

#200 Removed download of pre-trained models from automatically run tests
  .github/workflows/coverage.yml
  .github/workflows/pretrained_model.yml
  tests/compilation/test_predictor_rl.py
  tests/compilation/test_pretrained_models.py
  tests/device_selection/test_helper_ml.py
  tests/device_selection/test_predictor_ml.py
Labels: continuous integration

#201 🐛 fixed pretrained model tests
  .github/workflows/pretrained_model.yml
Labels: bug, continuous integration

#202 🎨 remove newly created model after usage
  tests/compilation/test_predictor_rl.py
Labels: enhancement, continuous integration

#187 👽️ update code to integrate new bench device class (dropped Python 3.9 support)
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  docs/conf.py
  evaluations/supervised_ml_models/evaluation.ipynb
  pyproject.toml
  src/mqt/predictor/Calibration.py
  src/mqt/predictor/Result.py
  src/mqt/predictor/evaluation.py
  src/mqt/predictor/ml/Predictor.py
  src/mqt/predictor/ml/helper.py
  src/mqt/predictor/ml/training_data/trained_model/trained_clf_expected_fidelity.joblib
  src/mqt/predictor/reward.py
  src/mqt/predictor/rl/PredictorEnv.py
  src/mqt/predictor/rl/helper.py
  src/mqt/predictor/utils.py
  tests/compilation/test_helper_rl.py
  tests/compilation/test_predictor_rl.py
  tests/compilation/test_pretrained_models.py
  tests/device_selection/test_helper_ml.py
  tests/device_selection/test_predictor_ml.py
  tests/test_calibration.py
  tests/test_evaluation.py
  tests/test_result.py
  tests/test_reward.py
Labels: enhancement, minor

#205 ✨ moved helper function from mqt bench to predictor
  src/mqt/predictor/reward.py
Labels: enhancement

#204 Improved Action Space incl. Layouting and BQSKit Integration
  .github/workflows/coverage.yml
  pyproject.toml
  src/mqt/predictor/ml/Predictor.py
  src/mqt/predictor/rl/Predictor.py
  src/mqt/predictor/rl/PredictorEnv.py
  src/mqt/predictor/rl/helper.py
  tests/compilation/test_helper_rl.py
  tests/compilation/test_integration_further_SDKs.py
  tests/compilation/test_predictor_rl.py
  tests/device_selection/test_helper_ml.py
  tests/device_selection/test_predictor_ml.py
  tests/test_pretrained_models.py
Labels: enhancement, feature, minor
