Repository munich-quantum-toolkit/predictor, pull requests merged in 2024-05, with the labels that each got.

#220 ✨ CI/CD Update
  .github/codecov.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  .github/workflows/mypy.yml
  .github/workflows/pretrained_model.yml
  README.md
  noxfile.py
  pyproject.toml
  src/mqt/predictor/utils.py
  tests/device_selection/test_predictor_ml.py
  tests/test_pretrained_models.py
Labels: enhancement, continuous integration

#223 📝 Fix MQT Logo in README
  README.md
  docs/_static/erc_dark.svg
  docs/_static/erc_light.svg
  docs/_static/logo-bavaria.svg
  docs/_static/logo-mqv.svg
  docs/_static/tum_dark.svg
  docs/_static/tum_light.svg
  docs/_templates/page.html
Labels: documentation

#225 📝 Add docstring check to ruff and fix respective errors
  pyproject.toml
  src/mqt/predictor/__init__.py
  src/mqt/predictor/evaluation.py
  src/mqt/predictor/ml/__init__.py
  src/mqt/predictor/ml/helper.py
  src/mqt/predictor/ml/predictor.py
  src/mqt/predictor/result.py
  src/mqt/predictor/reward.py
  src/mqt/predictor/rl/__init__.py
  src/mqt/predictor/rl/helper.py
  src/mqt/predictor/rl/predictor.py
  src/mqt/predictor/rl/predictorenv.py
  src/mqt/predictor/utils.py
  tests/__init__.py
  tests/compilation/test_helper_rl.py
  tests/compilation/test_integration_further_SDKs.py
  tests/compilation/test_predictor_rl.py
  tests/device_selection/test_helper_ml.py
  tests/device_selection/test_predictor_ml.py
  tests/test_evaluation.py
  tests/test_pretrained_models.py
Labels: documentation, enhancement

#231 🚨 fixed warnings that occurred due to new pytket and qiskit version
  pyproject.toml
  src/mqt/predictor/rl/helper.py
Labels: enhancement

#230 🧱 switched from mqt-core to mqt-workflows for CI workflows
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: continuous integration

#233 ⬆️ update black version in blacken-docs
  .pre-commit-config.yaml
Labels: dependencies, continuous integration
