Repository munich-quantum-toolkit/predictor, pull requests merged in 2025-09, with the labels that each got.

#450 📝 Improve changelog and upgrade guide
  CHANGELOG.md
  UPGRADING.md
Labels: documentation

#458 🐛 Fix broken check condition in CI
  .github/workflows/ci.yml
Labels: continuous integration, fix

#453 👷 Fix version of `pypa/gh-action-pypi-publish` Action
  .github/workflows/cd.yml
  CITATION.bib
  docs/refs.bib
Labels: continuous integration

#468 👷 Fix `minimums` nox session
  .gitignore
  noxfile.py
  pyproject.toml
  tests/compilation/test_reward.py
  uv.lock
Labels: dependencies, python
