Repository munich-quantum-toolkit/predictor, pull requests merged in 2025-07, with the labels that each got.

#395 👷 Enable templating
  .github/workflows/templating.yml
Labels: continuous integration

#394 ✨ introduce hatchling
  .readthedocs.yaml
  docs/conf.py
  noxfile.py
  pyproject.toml
  tests/device_selection/test_predictor_ml.py
  uv.lock
Labels: enhancement, continuous integration, packaging

#393 ✨ Update to support MQT Bench v2
  README.md
  docs/DeviceSelection.rst
  docs/Quickstart.ipynb
  docs/Usage.rst
  pyproject.toml
  src/mqt/predictor/hellinger/utils.py
  src/mqt/predictor/ml/helper.py
  src/mqt/predictor/ml/predictor.py
  src/mqt/predictor/reward.py
  src/mqt/predictor/rl/helper.py
  src/mqt/predictor/rl/predictor.py
  src/mqt/predictor/rl/predictorenv.py
  src/mqt/predictor/utils.py
  tests/compilation/test_helper_rl.py
  tests/compilation/test_integration_further_SDKs.py
  tests/compilation/test_predictor_rl.py
  tests/compilation/test_reward.py
  tests/device_selection/test_helper_ml.py
  tests/device_selection/test_predictor_ml.py
  tests/hellinger_distance/test_estimated_hellinger_distance.py
  uv.lock
Labels: dependencies, minor

#401 🎨 Improve RL Action Handling
  CHANGELOG.md
  docs/Usage.rst
  src/mqt/predictor/rl/actions.py
  src/mqt/predictor/rl/helper.py
  src/mqt/predictor/rl/parsing.py
  src/mqt/predictor/rl/predictor.py
  src/mqt/predictor/rl/predictorenv.py
  tests/compilation/test_helper_rl.py
  tests/compilation/test_integration_further_SDKs.py
  tests/compilation/test_predictor_rl.py
Labels: enhancement, refactor

#403 ♻️ Refactor ML Part
  .github/contributing.md
  .github/contributing.rst
  .github/support.md
  .github/support.rst
  CHANGELOG.md
  CITATION.bib
  docs/CHANGELOG.md
  docs/Compilation.rst
  docs/Contributing.rst
  docs/DevelopmentGuide.rst
  docs/DeviceSelection.rst
  docs/FigureOfMerit.rst
  docs/Quickstart.ipynb
  docs/References.rst
  docs/Support.rst
  docs/UPGRADING.md
  docs/Usage.rst
  docs/compilation.md
  docs/conf.py
  docs/contributing.md
  docs/development_guide.md
  docs/device_selection.md
  docs/figure_of_merit.md
  docs/index.md
  docs/index.rst
  docs/installation.md
  docs/quickstart.md
  docs/references.md
  docs/refs.bib
  docs/setup.md
  docs/support.md
  pyproject.toml
  src/mqt/predictor/__init__.py
  src/mqt/predictor/ml/__init__.py
  src/mqt/predictor/ml/helper.py
  src/mqt/predictor/ml/predictor.py
  src/mqt/predictor/qcompile.py
  src/mqt/predictor/reward.py
  src/mqt/predictor/rl/__init__.py
  src/mqt/predictor/rl/helper.py
  src/mqt/predictor/rl/predictor.py
  src/mqt/predictor/rl/predictorenv.py
  tests/compilation/test_helper_rl.py
  tests/compilation/test_predictor_rl.py
  tests/compilation/test_reward.py
  tests/device_selection/test_helper_ml.py
  tests/device_selection/test_predictor_ml.py
  tests/hellinger_distance/test_estimated_hellinger_distance.py
  uv.lock
Labels: documentation, enhancement, minor, refactor

#414 🔖 prepare the v2.3 release
  CHANGELOG.md
  UPGRADING.md
Labels: documentation, continuous integration
